Fix: Add missing base ShapeAppearanceOverlay style
The Android resource linker was failing because it couldn't find the base
ShapeAppearanceOverlay style that is referenced by child styles. This is a
Material Design 3 component that must be defined.

Error was:
  ERROR: AAPT: error: resource style/ShapeAppearanceOverlay (aka 
  com.movtery.zalithlauncher.debug:style/ShapeAppearanceOverlay) not found.

Fixes: #build-error